DROP DATABASE UserDatabase;
CREATE DATABASE UserDatabase;
USE UserDatabase;
DROP TABLE csit314.Users;

CREATE TABLE csit314.Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(100) NOT NULL,
    UserType ENUM('Admin', 'REA', 'Buyer', 'Seller') NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);